version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/app

permission:
  - object: /home/ubuntu/app
    owner: ubuntu
    group: ubuntu

hooks:
  BeforeInstall:
    - location: scripts/before_deploy.sh
      runas: ubuntu

  AfterInstall:
    - location: scripts/after_deploy.sh
      runas: ubuntu