# This is a basic workflow to help you get started with Actions

name: CI/CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout source code
        uses: actions/checkout@v3
      
      - name: Build client
        working-directory: ./client
        run: |
          yarn install
          CI='' REACT_APP_API_URL=$url yarn build
        env:
          url: ${{ secrets.API_URL }}

      - name: Build server
        run: |
          yarn install
          CI='' yarn build

      - name: Zip files
        run: zip -r ./$GITHUB_SHA.zip build client/build appspec.yml nginx scripts docker-compose.yml Dockerfile package.json yarn.lock
        shell: bash
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: Delete files on S3
        run: aws s3 rm s3://stock-b/ --recursive --include "*"

      - name: Upload zip file to S3
        run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://stock-b/app/$GITHUB_SHA.zip

      - name: Code deploy
        run: aws deploy create-deployment
          --application-name stock
          --deployment-config-name CodeDeployDefault.AllAtOnce
          --deployment-group-name stock-group
          --s3-location bucket=stock-b,key=app/$GITHUB_SHA.zip,bundleType=zip